default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: clubReady_development


test:
  <<: *default
  database: clubReady_test

  production:
    host: <%= ENV['DATABASE_URL'] %>
    database: clubReady_production